apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    {{- include "boltz2-nim-chart.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:
    path: {{ .Values.persistence.hostPath | quote }}
